name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    # 1. GitHub Environment → enables approval for prod
    environment: ${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      # 2. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 3 Setup Terraform (BEST PRACTICE)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6 # pin version
          terraform_wrapper: false # avoids noisy logs

      # 4. Configure AWS credentials (OIDC)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ vars.REGION }}

      # 5. Terraform Init (remote backend per env)
      - name: Terraform Init
        working-directory: envs/${{ github.event.inputs.environment }}
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.BUCKET }}" \
            -backend-config="key=s3-static-website/${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION}}" \

      # 6. Terraform Plan
      - name: Terraform Plan
        working-directory: envs/${{ github.event.inputs.environment }}
        run: |
          terraform plan \
            -var="bucket_name=${{ secrets.BUCKET_NAME}}" \
            -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
            -var="project_name=${{ vars.PROJECT_NAME }}" \
            -var="environment=${{ github.event.inputs.environment }}" \
            -var="s3_origin_id=${{ vars.S3_ORIGIN_ID }}" \
            -var="hosted_zone_id=${{ secrets.HOSTED_ZONE_ID }}" \
            -out=tfplan

      # 7. Terraform Apply
      - name: Terraform Apply
        working-directory: envs/${{ github.event.inputs.environment }}
        run: terraform apply -auto-approve tfplan

      # 8. Deploy the static website to S3
      - name: Deploy Static Website to S3
        # if: ${{ github.event.inputs.environment != 'prod' }}
        # working-directory: envs/${{ github.event.inputs.environment }}
        run: |
          aws s3 sync ../../website-content/ s3://${{ secrets.BUCKET_NAME }} --delete
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}

      # 9. Output website URL
      - name: Output Website URL
        working-directory: envs/${{ github.event.inputs.environment }}
        run: |
          terraform output website_url
